src/Entity/Participant.php
<?php

namespace App\Entity;

use App\Repository\ParticipantRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity;
use Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface;
use Symfony\Component\Security\Core\User\UserInterface;
use Symfony\Component\Validator\Constraints as Assert;

#[ORM\Entity(repositoryClass: ParticipantRepository::class)]
#[UniqueEntity(fields: ['username'], message: "Le nom d'utilisateur est déjà utilisé")]
class Participant implements UserInterface, PasswordAuthenticatedUserInterface
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(length: 180, unique: true)]
    #[Assert\Email(message: "Email non valide")]
    #[Assert\NotNull(message: "L'email ne doit pas être vide")]
    private ?string $email = null;

    #[ORM\Column]
    private array $roles = [];

    /**
     * @var string The hashed password
     */
    #[ORM\Column]
    #[Assert\PasswordStrength(message: "Le mot de passe n'est pas assez fort")]
    #[Assert\NotNull(message: "Le mot de passe ne doit pas être vide")]
    private ?string $password = null;

//    #[Assert\Unique(message: "Le nom d'utilisateur est déjà utilisé", fields: ['username'])]
    #[Assert\Length(min: 5, max: 30, minMessage: "le pseudo doit faire minimum 5 caractères", maxMessage: "le nom doit faire maximum 15 caractères")]
    #[Assert\NotNull(message: "Le nom d'utilisateur ne doit pas être vide")]
    #[ORM\Column(length: 30, unique: true)]
    private ?string $username = null;

    #[ORM\Column(length: 30)]
    #[Assert\Length(min: 2, max: 30, minMessage: "le nom doit faire minimum 2 caractères", maxMessage: "le nom doit faire maximum 30 caractères")]
    #[Assert\NotNull(message: "Le nom ne doit pas être vide")]
    private ?string $lastName = null;

    #[ORM\Column(length: 30)]
    #[Assert\Length(min: 2, max: 30, minMessage: "le prenom doit faire minimum 2 caractères", maxMessage: "le prenom doit faire maximum 30 caractères")]
    #[Assert\NotNull(message: "Le prénom ne doit pas être vide")]
    private ?string $firstName = null;

    #[ORM\Column(length: 15, nullable: true)]
    #[Assert\Length(min: 10, max: 20, minMessage: "Votre numéro de téléphone doit contenir au moins 10 caractères", maxMessage: "Votre numéro de téléphone doit contenir moins de 20 caractères")]
    #[Assert\Regex(pattern: "/^[0-9+\s]*$/", message: "Veuillez entrer un numéro de téléphone valide")]
    private ?string $telephone = null;


    #[ORM\Column]
    private ?bool $active = null;

    #[ORM\ManyToOne(inversedBy: 'participants')]
    #[ORM\JoinColumn(nullable: false)]
    private ?Site $site = null;


    #[ORM\Column(length: 500, nullable: true)]
    private ?string $photoUrl = null;

    #[ORM\ManyToMany(targetEntity: Outing::class, mappedBy: 'participants')]
    private Collection $outings;

    public function __construct()
    {
        $this->outings = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getEmail(): ?string
    {
        return $this->email;
    }

    public function setEmail(?string $email): static
    {
        $this->email = $email;

        return $this;
    }

    /**
     * A visual identifier that represents this user.
     *
     * @see UserInterface
     */
    public function getUserIdentifier(): string
    {
        return (string) $this->email;
    }

    /**
     * @see UserInterface
     */
    public function getRoles(): array
    {
        $roles = $this->roles;
        // guarantee every user at least has ROLE_USER
        $roles[] = 'ROLE_USER';

        return array_unique($roles);
    }

    public function setRoles(array $roles): static
    {
        $this->roles = $roles;

        return $this;
    }

    public function isAdmin(): bool
    {
        return in_array("ROLE_ADMIN",$this->roles);
    }

    /**
     * @see PasswordAuthenticatedUserInterface
     */
    public function getPassword(): ?string
    {
        return $this->password;
    }

    public function setPassword(?string $password): static
    {
        $this->password = $password;

        return $this;
    }

    /**
     * @see UserInterface
     */
    public function eraseCredentials(): void
    {
        // If you store any temporary, sensitive data on the user, clear it here
        // $this->plainPassword = null;
    }

    public function getUsername(): ?string
    {
        return $this->username;
    }

    public function setUsername(?string $username): static
    {
        $this->username = $username;

        return $this;
    }

    public function getLastName(): ?string
    {
        return $this->lastName;
    }

    public function setLastName(?string $lastName): static
    {
        $this->lastName = $lastName;

        return $this;
    }

    public function getFirstName(): ?string
    {
        return $this->firstName;
    }

    public function setFirstName(?string $firstName): static
    {
        $this->firstName = $firstName;

        return $this;
    }

    public function getTelephone(): ?string
    {
        return $this->telephone;
    }

    public function setTelephone(?string $telephone): static
    {
        $this->telephone = $telephone;

        return $this;
    }

    public function isActive(): ?bool
    {
        return $this->active;
    }

    public function setActive(bool $active): static
    {
        $this->active = $active;

        return $this;
    }

    public function getSite(): ?Site
    {
        return $this->site;
    }

    public function setSite(?Site $site): static
    {
        $this->site = $site;

        return $this;
    }

    public function getPhotoUrl(): ?string
    {
        return $this->photoUrl;
    }

    public function setPhotoUrl(?string $photoUrl): static
    {
        $this->photoUrl = $photoUrl;

        return $this;
    }

    /**
     * @return Collection<int, Outing>
     */
    public function getOutings(): Collection
    {
        return $this->outings;
    }

    public function addOuting(Outing $outing): static
    {
        if (!$this->outings->contains($outing)) {
            $this->outings->add($outing);
            $outing->addParticipant($this);
        }

        return $this;
    }

    public function removeOuting(Outing $outing): static
    {
        if ($this->outings->removeElement($outing)) {
            $outing->removeParticipant($this);
        }

        return $this;
    }
}

templates/inc/footer.html.twig
<div class="footer c">

</div>

templates/inc/header.html.twig
<div class="header container">
    <div class="header-logo">
        <a href="{{ path('outing_search') }}">
            <img src="{{ asset('img/icon/logoExit.png') }}" alt="logo qui rappel la nature et les couleurs de notre site internet">
        </a>
    </div>
    <label class="burger" for="burger">
        <input type="checkbox" id="burger">
        <span></span>
        <span></span>
        <span></span>
    </label>
    <nav class="header-nav" id="navMenu">
        <ul>
            {% if app.user %}
                {% if app.user.admin %}
                    <li><a href="{{ path('app_city') }}" title="Villes">Villes</a></li>
                    <li><a href="{{ path('app_site') }}" title="Sites">Sites</a></li>
                {% endif %}
            {% endif %}
            <li> <a href="{{ path('outing_search') }}" title="Accueil">Accueil</a></li>
            {% if app.user %}
                <li class="profile-picture"><span><img src="{{ asset('img/profile/' ~ app.user.photoUrl) }}" alt="profile picture"></span>
                    <ul>
                        <li><a href="{{ path('app_user_profile', {'id': app.user.id}) }}">Voir mon profil</a></li>
                        <li><a href="{{ path('app_edit_profile', {'id': app.user.id}) }}">Modifier mon profil</a></li>
                        <li><a href="{{ path('app_logout') }}" title="Se déconnecter">Se déconnecter</a></li>
                    </ul>
                </li>
            {% endif %}
            {% if not app.user %}
                <li><a href="{{ path('app_login') }}" title="Se connecter">Se connecter</a></li>
            {% endif %}
                {% if app.user %}
                    <ul id="userMenu" class="userMenu">
                        <li><a href="{{ path('app_user_profile', {'id': app.user.id}) }}">Voir mon profil</a></li>
                        <li><a href="{{ path('app_edit_profile', {'id': app.user.id}) }}">Modifier mon profil</a></li>
                        <li class="last-border-bottom" style=""><a href="{{ path('app_logout') }}" title="Se déconnecter">Se déconnecter</a></li>
                    </ul>
                {% endif %}
        </ul>
    </nav>
</div>